### ISSUE TITLE
Clarify the scope of EnableJms

### ISSUE THREAD

**Issue by snicoll** [spring-guides/gs-messaging-jms#15]
see https://stackoverflow.com/questions/45796021/how-does-spring-look-for-enablejms-methods-if-i-dont-have-class-marked-enable

**Comment by serdarosmanonur** [comment]
I think the Getting started guide has not been updated yet [see here](https://spring.io/guides/gs/messaging-jms/).
This guide should be updated. Purpose of @EnableJms annotation should be made clear. When we need @EnableJms and when we don't is not clear in the guide, nor is the purpose. For example, as the StackOverflow discussion linked by @snicoll states, do we really need the @EnableJms annotation together with @SpringBootApplication? These types of redundancies will create questions and confusions in people's minds.

**Comment by snicoll** [comment]
@serdarosmanonur the getting starteed guide has not been updated because this issue is still opened.

**Comment by serdarosmanonur** [comment]
@snicoll Thanks for the response Stephane. But that is not the point. The point is, after almost 2 years the fix has not been done. Therefore I wanted to draw some attention. Cheers.

**Comment by snicoll** [comment]
The guide is open source, feel free to submit a PR based on my answer on SO and I am happy to review it.

**Comment by gredwhite** [comment]
issue still open

**Comment by snicoll** [comment]
@gredwhite please consider reviewing the history before commenting.

**Comment by fml2** [comment]
See #41.

**Comment by snicoll** [comment]
Thanks @fml2! 

Closing in favor of PR #41.
