### ISSUE TITLE
JmsTemplate should use a `CachingConnectionFactory`

### ISSUE THREAD

**Issue by mminella** [spring-guides/gs-messaging-jms#20]
When using a `JmsTemplate`, it is a best practice to use a `CachingConnectionFactory`.  This guide leaves that out.  There currently is no Bootiful way to create one, but I created this issue requesting it: https://github.com/spring-projects/spring-boot/issues/13065

**Comment by Buzzardo** [comment]
I wonder if that ability has been added. I bet @garyrussell would know (or know who does know).
