### ISSUE TITLE
how to achieve broadcast by multiple JMS Listeners with the same destination

### ISSUE THREAD

**Issue by Linuxea** [spring-guides/gs-messaging-jms#29]
I copy a class named <code>Receiver2</code> from class <code>Receiver</code>, but the two listeners was triggered only one of them.

How to achieve broadcast by multiple JMS listeners with the same destination?

I had try invoke<code>DefaultJmsListenerContainerFactory#setConcurrency </code> with argument <code>'2'</code> but it does not work.

**Comment by snicoll** [comment]
I am afraid that's a question that best suited for StackOverflow. A queue has one and only one receiver. If you want to broadcast, you need to use a topic.
