### ISSUE TITLE
Adding @ComponentScan annotation to add DAO component breaks Jms listener

### ISSUE THREAD

**Issue by mateobencek** [spring-guides/gs-messaging-jms#33]
Adding DAO component as dependency breaks Jms service and the process starts and ends almost immediately.
To reproduce:
have a working Jms service and try to add DAO dependency with @ComponentScan("dao.package")

**Comment by snicoll** [comment]
Sorry but I am not sure what you mean by that. Please ask on Stackoverflow with a small sample.
