### ISSUE TITLE
Dependencies should be listed clearly.

### ISSUE THREAD

**Issue by jkkj** [spring-guides/gs-messaging-jms#42]
I built the project by the Spring Initializer on VS Code and I had to check this github repo code for the differences because after all the steps I followed the app had not worked. I believe the dependecies `artemis-jakarta-server` and `spring-boot-starter-json` should be clearly stated in the tutorial.

**Comment by snicoll** [comment]
> I had to check this github repo code for the differences because after all the steps I followed the app had not worked. 

By all the steps, do you mean following the guide? Both those dependencies [are listed](https://spring.io/guides/gs/messaging-jms/). Can you clarify?

**Comment by snicoll** [comment]
Closing due to the lack of requested feedback.

**Comment by snicoll** [comment]
> I believe this is suboptimal. Especially for new users who don't have much clue yet (it's a tutorial after all).

OK. If following the guide is too complicated, what would you recommend then?
