### ISSUE TITLE
Upgrade to latest Spring Boot version

### ISSUE THREAD

**Issue by Buzzardo** [spring-guides/gs-messaging-jms#43]
An easy place to get started with contributing to Spring is keeping the Spring Boot version up-to-date, so I'm adding this issue as an invitation to first-time contributors.

You need to set the Spring Boot version in:

* `initial/build.gradle`
* `initial/pom.xml`
* `complete/build.gradle`
* `complete/pom.xml`

Then run `test/run.sh` to validate the upgrade worked as expected.

**Comment by robertmcnees** [comment]
Dependabot is now being used in this project to upgrade minor version releases. There is an opportunity for contributors to upgrade patch versions, but this will be tracked with a different issue in a different project.
