### ISSUE TITLE
Remove unused CI files

### ISSUE THREAD

**Issue by robertmcnees** [spring-guides/gs-messaging-jms#45]
The file `test/run.sh` is no longer required. This file and the `test` directory can be deleted.

The file was originally used for Jenkins CI. Now that this project has been converted to GitHub Actions, this file can be removed.

**Comment by bigbaliboy** [comment]
Hey @robertmcnees , can you assign this to me?

**Comment by robertmcnees** [comment]
Hi @bigbaliboy. In general, we don't assign issues but keep them open for anyone in the community.

I saw your PR and merged it in. Thanks for the PR! I'll close this issue.
